export const CLOSE_MODAL_EDIT = "CLOSE_MODAL_EDIT";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER"