export const SET_USER_INFO = "SET_USER_INFO"
export const GET_USER = "GET_USER"
export const GET_USER_BY_PROJECT = "GET_USER_BY_PROJECT"
export const GET_USER_LIST = "GET_USER_LIST"
export const EDIT_USER = "EDIT_USER"
